services:
  - type: web
    name: hirebotics-backend
    env: python
    buildCommand: "./venv/Scripts/pip install -r requirements.txt && python manage.py collectstatic --no-input"
    startCommand: "gunicorn hirebotics.wsgi --log-file -"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: hirebotics.settings
      - key: SECRET_KEY
        sync: false

  - type: web
    name: hirebotics-frontend
    env: static
    staticPublishPath: frontend/build
    buildCommand: "cd frontend && npm install && npm run build"
